### ISSUE TITLE
Suggestion: Move read_measurement_table into WhiskerMeasurementTable class or __init__.py

### ISSUE THREAD

**Issue by rly** [vncntprvst/ndx-whisk#1]
The `read_measurement_table` function seems very useful for anyone working with this extension. I think it would be nice to package that function into the ndx-whisk package so that people working with WhiskiWrap can use it too to populate the `WhiskerMeasurementTable`. It could live in the `WhiskerMeasurementTable` class or just in `./src/ndx_whisk/__init__.py` as a standalone function.

**Comment by vncntprvst** [comment]
Thanks for the comment! I did some update in that direction yesterday, on the WhiskiWrap code base. I will add it to ndx-whisk as well.

**Comment by vncntprvst** [comment]
Actually, now that the function is [added to WhiskiWrap](https://github.com/vncntprvst/WhiskiWrap/blob/c894a229512d32db689d3741cda9b3c5135c91ad/WhiskiWrap/base.py#L491), I think it makes more sense not to duplicate the function here. It is only useful if using WhiskiWrap anyway, and I'd like to extend `ndx-whisk` to other whisker trackers at some point - or at least it keep compatible.

**Comment by rly** [comment]
Sounds good
